name: auto-sync-fork
on:
  workflow_dispatch:

permissions: read-all

jobs:
  auto-sync-fork:
    name: Sync fork
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: "gh repo sync"
        id: gh-repo-sync
        run: |
          echo ${{ github.token }} >> gh auth login --with-token
          gh auth refresh -s workflow --hostname ${{ github.server_url }}
          gh repo sync ${{ github.repository }} -b main
