name: auto-sync-fork
on:
  workflow_dispatch:

permissions: read-all

jobs:
  auto-sync-fork:
    name: Sync fork
    runs-on: ubuntu-latest
    steps:
      - name: "gh repo sync"
        id: gh-repo-sync
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh repo sync ${{ github.repository }} -b main
